name: release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write

jobs:
  # Create the release the build job attaches to.
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  # Windows prebuilt binary.
  windows:
    name: Windows
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          targets: x86_64-pc-windows-msvc

      - name: Build release binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Package artifact
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "target/x86_64-pc-windows-msvc/release/wowsdeob.exe","README.md" `
            -DestinationPath "wowsdeob_${{ github.ref_name }}_win64.zip"

      - name: Attach to release
        uses: softprops/action-gh-release@v2
        with:
          files: wowsdeob_${{ github.ref_name }}_win64.zip
